version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    container_name:  ${DOCKER_NAME}-nginx
    ports:
      - 8400:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - networkapp

  app:
    env_file:
      - .env
    build:
      args:
        user: user
        uid: 1000
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: ${DOCKER_NAME}-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - networkapp

  mysql:
    image: "mysql:8.0"
    container_name: ${DOCKER_NAME}-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      SERVICE_NAME: mysql
    ports:
      - 36649:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - networkapp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${DOCKER_NAME}-phpmyadmin"
    links:
      - mysql:mysql
    ports:
      - 7800:80
    environment:
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      PMA_HOST: mysql
    networks:
      - networkapp

networks: 
  networkapp:
    driver: bridge